# Generated by Django 4.0.6 on 2022-07-12 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='following_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user.user'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user.user'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('1', '남자'), ('2', '여자')], max_length=5, null=True, verbose_name='성별')),
                ('is_active', models.BooleanField(default=True, verbose_name='공개여부')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='유저')),
            ],
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('type', models.CharField(choices=[('1', '강아지'), ('2', '고양이'), ('3', '기타')], max_length=5, verbose_name='종류')),
                ('gender', models.CharField(choices=[('1', '여자'), ('2', '남자'), ('3', '모름')], default='3', max_length=5, verbose_name='성별')),
                ('size', models.CharField(choices=[('1', '소형'), ('2', '중형'), ('3', '대형')], max_length=5, verbose_name='사이즈')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='보호자', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
